PVAYLADEV-1093: Restructured and updated XRd4J-documentation to improve readability
vrk-kpa/xrd4j pull request #14
Opened 2018-03-15 13:17 UTC by tmkrepo

Includes:
- XRd4J documented version updated to 0.2.0
- added information on CSC snapshot repository
- modified documentation references to `request` and `response` elements regarding default wrapper setting change
- README.md refactored to have only basic information on library purpose and structure,  including the library to a project, developing the library itself and developing an adapter utilizing the library
  * more detailed adapter implementation instructions with examples now moved to [adapter implementation document](master...PVAYLADEV-1093#diff-1ffe650155791561b26bf1481107e05a)
  * implementation examples for adapter server now refer directly to example-adapter code (old code examples were separate code blocks of an adapter that implemented just helloService)
  * while still not perfect, this alleviates the maintenance load of separate code blocks when library code changes; reference line numbering and structure still need to be kept up to date though (as well as example-adapter, but that is a given)
-  small stylistic changes to other additional documentation under documentation-directory

2018-03-21 15:02 UTC, iluwatar requested changes

2018-03-21 15:02 UTC, iluwatar commented on README.md
> +### Releases
Suggestion: `#### Release Repository` to match `#### Snapshot Repository` below

2018-03-21 15:02 UTC, iluwatar commented on documentation/Import-a-Certificate-as-a-Trusted-Certificate.md
>  https://mysecurityserverver.com/
https://mysecurityserverver.com:4000 would be more realistic

2018-03-21 15:02 UTC, iluwatar commented on documentation/Setting-up-Development-Environment.md
>  mvn clean install
Enhancement proposal: The section `### IDE Setup` below could be removed since the content is so shallow

2018-03-21 15:02 UTC, iluwatar commented on documentation/Setting-up-SSL-on-Tomcat.md
>  #### 4. How to configure web applications for SSL
-> How to configure web applications for SSL only

or 

-> How to disable HTTP

2018-03-28 13:44 UTC, tmkrepo commented on documentation/Setting-up-Development-Environment.md
>  mvn clean install
Section removed

2018-03-29 06:22 UTC, merged